name: Try Matrix
on: push

jobs:
  runtest:
    strategy:
      matrix:
        batches0: ["['B1']","['B2']"]
    runs-on: ubuntu-latest
    steps:
      - name: Echo something
        run: echo " ${{ toJSON ( matrix.batches0 ) }} "
 
