name: Try Matrix
on: push

jobs:
  runtest:
    strategy:
      matrix:
        batches: ["B1", "B2", "B3"]
    runs-on: ubuntu-latest
    steps:
      - name: Echo something
        run: echo "something "
 
